name = "cloudflare-graphql-d1"
main = "src/index.ts"
compatibility_date = "2024-02-23"
node_compat = true
minify = true

[env.preview]
[[d1_databases]]
binding = "DB"   
database_name = "test-db"
database_id = "3d4faa53-b8d7-45ec-8cb5-e4608d0fef2d"
preview_database_id = "test-db"
