name = "cloudflare-graphql-d1"
main = "src/index.ts"
compatibility_date = "2024-03-14"
node_compat = true
minify = true

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id ="2c952269-9eb1-4063-8fbe-08a3530925f0"

[env.local]
d1_databases=[
  {binding = "DB",database_name = "test-db",database_id ="test-db"}
]
